config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # next line added 14 may 17
  root 'quotes#index'
  # next line added 16 may 17
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
    # next line added 16 may 17
    validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
    validates :author, presence: true, length: { maximum: 50, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    # next 4 lines added 14 may 17
    def index
        # @quote = Quote.first
        @quote = Quote.order("RANDOM()").first
    end

# next 16 lines added 16 may 17, then these 3 lines deleted
#    def new
#        @quote = Quote.new
#    end

    def create
        @quote = Quote.create(quote_params)
        if @quote.invalid?
            flash[:error] = '<strong>Could not save</strong>, the data you entered is invalid.'
        end
        redirect_to root_path
    end
    
    def about
    end
    
    private
    
    def quote_params
        params.require(:quote).permit(:saying, :author)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- next 21 lines added 15 may 17 -->
    <header class="row">
      
      <div class="col-3">
        
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
          <br />
          You know
          <br />
          you need
          <br />
          to code
          </div>
        <% end %>
        
      </div>
<!-- next line modified 17 may 17 -->
      <div class="col col-sm-4 hidden-xs-down slogan">
        Splurting out unsolicited advice since 2017
      </div>

<!-- next line added 17 may 17 -->
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
<!--      <div class="col-5 links">   deleted 17 may 17  -->
<!--        <%= link_to 'Contribute', new_quote_path %> -->
      <!-- modal lines added 16 may 17 -->
      <!-- Button trigger modal
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Launch demo modal
        </button>  -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About', about_path %>
      </div>
      
    </header>
    
    <!-- modal lines added 16 may 17 -->
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute your quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "What is the saying you want to add?", placeholder: "Fear is the disease. Hustle is the antidote." %>
              <br />
              <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Travis Kalanick" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    
    
    <hr />
    
    <br class="clear" />
    <!-- next 6 lines added 16 may 17 -->
    <div class="container">
      <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
      <% end %>
      <%= yield %>
    <!-- next 8 lines added 16 may 17 -->
    </div>
    
    <div class="footer">
      <div class="container">
        <div class="row">
<!--          <div class="col-6">  deleted 17 may 17  -->
          <div class="col-12 col-sm-6">
            <%= link_to "This isn't enough, I need more", root_path, class: "next-quote" %>
          </div>
<!--          <div class="col-6 footer-blurb">  deleted 17 may 17  -->
          <div class="col-12 col-sm-6 footer-blurb">
            Part of a student project by <a href="https://www.linkedin.com/in/victorchristensen">Victor Christensen</a><br />
            Want to build your own Splurty Web App - <a href="http://thefirehoseproject.com">Learn how to code here</a>
          </div>
<!--          <p class="text-muted">Place sticky footer content here.</p>  -->
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/quotes/about.html.erb
<!-- firehose track 2, lesson 14 - file created 16 may 17 -->

<div class="col-10 offset-1 about">
    <h1>About Splurty</h1>
    
    <br />
    <p>
        Splurty was built by Victor Christensen as part of the Firehose Project Bootcamp.
    </p>
    <br />
    <p>
        If you want to learn how to code - start <a target="_blank" href="http://www.thefirehoseproject.com/"> here</a>.
    </p>
    
    <div class="row">
        <div class="col-12 col-sm-4">
            <%= image_tag 'Victor Christensen-firehose.jpg', class: 'img-fluid' %>
        </div>
        <div class="col-12 col-sm-7 offset-sm-1">
            <h2 class="text-center">Victor Christensen</h2>
            <br />
            <p>
                Victor Christensen is a student web developer, currently getting a long drink from the Firehose Project. His background includes technical writing and information security. See more about him <a target="_blank" href="https://www.linkedin.com/in/victorchristensen">here</a>.
            </p>
        </div>
    </div>

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<!-- next 8 lines added/modified 14/17 may 17
<h1>Welcome to ET's Awesome Web App</h1>
<h1><%= @quote.inspect %></h1> -->

<h2>
    <span>Splurty / No. <%= @quote.id %></span>
    Here's the <u>best unsolicited startup advice</u> you can get!
</h2>
<br />
<br />
<br />
<h1><%= @quote.saying %></h1>
<h2 class="float-right">~ <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />